<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <RevitVersion>2025</RevitVersion>
  </PropertyGroup>

  <!-- Net Core -->
  <PropertyGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitVersion).*" IncludeAssets="build; compile" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Isolator.Fody\Isolator.Fody.csproj" ReferenceOutputAssembly="false" PrivateAssets="All" />
    <WeaverFiles Include="..\Isolator.Fody\bin\$(Configuration)\netstandard2.0\Isolator.Fody.dll" />
  </ItemGroup>

  <PropertyGroup>
    <WeaverConfiguration>
      <Weavers>
        <Isolator />
      </Weavers>
    </WeaverConfiguration>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Isolator\Isolator.csproj" PrivateAssets="All" />
  </ItemGroup>

</Project>
