<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <DisableFody>true</DisableFody>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FodyHelpers" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Isolator.Template\Isolator.Template.csproj" PrivateAssets="All" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Isolator.Template\bin\$(Configuration)\netstandard2.0\Isolator.Template.dll">
      <Link>src\Template.netstandard2.0.dll</Link>
      <InProject>false</InProject>
      <LogicalName>Isolator.Template.netstandard2.0.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Isolator.Template\bin\$(Configuration)\net6.0\Isolator.Template.dll">
      <Link>src\Template.net6.0.dll</Link>
      <InProject>false</InProject>
      <LogicalName>Isolator.Template.net6.0.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Isolator.Template\bin\$(Configuration)\net8.0\Isolator.Template.dll">
      <Link>src\Template.net8.0.dll</Link>
      <InProject>false</InProject>
      <LogicalName>Isolator.Template.net8.0.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="$(MSBuildProjectDirectory)\..\Isolator.Template\Common.cs">
      <Link>src\Common.cs</Link>
      <InProject>false</InProject>
    </EmbeddedResource>
    <EmbeddedResource Include="$(MSBuildProjectDirectory)\..\Isolator.Template\ILTemplate.cs">
      <Link>src\ILTemplate.cs</Link>
      <InProject>false</InProject>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" GeneratePathProperty="true" />
    <EmbeddedResource Include="$(PkgMicrosoft_NETFramework_ReferenceAssemblies_net48)\build\.NETFramework\v4.8\Facades\netstandard.dll">
      <Link>src\netstandard.dll</Link>
      <InProject>false</InProject>
      <LogicalName>Isolator.NETFramework.netstandard.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Isolator.Template.Debug\Isolator.Template.Debug.csproj" PrivateAssets="All" ReferenceOutputAssembly="false" />
    <EmbeddedResource Include="..\Isolator.Template.Debug\bin\$(Configuration)\netstandard2.0\Isolator.Template.Debug.dll">
      <Link>src\Template.Debug.netstandard2.0.dll</Link>
      <InProject>false</InProject>
      <LogicalName>Isolator.Template.Debug.netstandard2.0.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Isolator.Template.Debug\bin\$(Configuration)\net6.0\Isolator.Template.Debug.dll">
      <Link>src\Template.Debug.net6.0.dll</Link>
      <InProject>false</InProject>
      <LogicalName>Isolator.Template.Debug.net6.0.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Isolator.Template.Debug\bin\$(Configuration)\net8.0\Isolator.Template.Debug.dll">
      <Link>src\Template.Debug.net8.0.dll</Link>
      <InProject>false</InProject>
      <LogicalName>Isolator.Template.Debug.net8.0.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>